### ISSUE TITLE
Q: Interpretation 

### ISSUE THREAD

**Issue by jdm204** [katharostech/katharos-license#2] opened 2021-02-07 09:03 UTC
Hi,

Is it possible to clarify what “supporting/promoting” is intended to convey here  - for example would games like Call of Duty or Mass Effect be supporting or promoting violence/warfare/sexually suggestive images?

**Comment by zicklag** [comment] 2021-02-08 03:33
Hi @jdm204, thanks for the issue. We're going to discuss it and I'll get back to you after that.

**Comment by zicklag** [comment] 2021-02-21 22:49
@jdm204 We did some evaluation of the current verbiage and we agree that it is rather ambiguous. We are doing some work to clarify the license terms and will put out a new revision that will hopefully be more clear as soon as we finish.

**Comment by PythonCoderUnicorn** [comment] 2021-08-29 21:01
I guess basic facts regarding the king james book (your source for ethical standards) would be ignored?
your source material has plenty of objectionable material that exceeds video games and other media. 
Also, code doesn't come with explicit content labels, even if it did, it would boost sales and attention. Look at the most popular music, most have explicit lyrics.

**Comment by tajmone** [comment] 2021-12-11 02:31
> your source material has plenty of objectionable material that exceeds video games and other media.
> Also, code doesn't come with explicit content labels, even if it did, it would boost sales and attention.

I might also add that video games "promote" fictional violence, for entertaining purposes, and players know that what they are indulging in is a virtual simulation, whereas the violence described and promoted in the Bible as being "morally righteous" is believed to be true and not fiction (at least by its followers).

This license makes little legal sense to me, especially the passage:

> The Katharos License is based on the premise that the full 66 books of the Holy Bible are 100% true and inspired by God and that He alone is the ultimate authority for what is good and just.

These 66 books include the Old Testament, so even from a Christian perspective the above sentence seems puzzling, based on the (Christian) believe that Christianity has (purportedly) superseded Judaism, which is why Christians don't follow the Judaic laws. It's obvious that these "66 books" require interpretation, i.e. by some clerical or theological authority to establish which is the "true word of G*d" when conflicting statements are  to be encountered in different books.

I'm not quite sure that a court which has to deliberate on a legal dispute concerning whether the terms of a software license have been violated or not is willing to go to the extent of calling in religious Bible experts to solve interpretational disputes on these matters. 

E.g. if I were to use a software component licensed under the Katharos License for a marketing campaign of pork sausages, would I be violating the license terms? According to the Old Testament pork meat is "inpure" (protecting "purity" and "pure acts" seems a central issue in this license, and the term "pure" in the Bible mostly refers to dietary, purification, and ritualistic practices), so this sounds like a license violation. One might argue that Christianity superseded the Jewish dietary laws, but that would be a religious interpretation, whereas a legal interpretation is most likely going to ignore any contradictions in the 66 books, and consider a violation of any of these precepts as a violation of the license, since the latter is a legal document and it claims that all 66 books are to be considered the "word of God" against which the license is to be measured.

Also, depending on _which_ Bible you're using as a reference, the number of books might differ from the "66 books" mentioned, as well as their contents — not to mention [apocrypha](https://en.wikipedia.org/wiki/Apocrypha), should the Gospel of Barnabas be counted?

Unless the license provides a specific Bible edition as a reference, even enthusiastic end users of this license might find it hard to know how to use it. 

I personally would not use software released under this license, it's too controversial, legally dubious, ethically skewed (to say the least) and introduces an unnecessary burden on its end users. Not to mention that in some countries it might not even be legal to use, since it might violate some state sanctioned religious dogmas.

I also suspect that this license is not entirely compliant with the GitHub EULA and guidelines, and definitely not aligned with the vision that drives the open source community, where we avoid getting into religious and political debates, since they usually end up disrupting collaboration — it only a takes one user who brings up ethical questions raised by the Book of Deuteronomy, and the debate will definitely turn sour.

**Comment by zicklag** [comment] 2021-12-11 02:57
Almost all of the points above have been brought up by other users in the Bevy Retrograde discussion ( https://github.com/katharostech/bevy_retrograde/issues/1 ) so I won't reply to them here. You can read through that issue if you would like our perspective on the matter.

The only new point is compliance with the GitHub EULA. I'm not aware of any issues with this, so unless you have evidence of something specific we are violating, then I don't think it's an issue.

**Comment by tajmone** [comment] 2021-12-11 03:27
> Almost all of the points above have been brought up by other users in the Bevy Retrograde discussion ( katharostech/bevy_retrograde#1 ) so I won't reply to them here. 

I've seen some of them, but doesn't it make more sense to discuss them here, since this is the official repository for the License?
I also became aware of this license via the Bevy project (which I wanted to use), but the reason I posted here is because I wanted to focus on the license specific discussion.

> The only new point is compliance with the GitHub EULA. I'm not aware of any issues with this, so unless you have evidence of something specific we are violating, then I don't think it's an issue.

As you noticed, I carefully chose the "not entirely compliant" words, and emphasized the question of the difference in vision, rather than legal matters.

I want to make it very clear that I'm a libertarian atheist, so I value very much freedom of speech of religion. 

My main concern here is that this license introduces some clauses which rub against the general spirit that drives the open source community, which (as mentioned) tries to avoid getting entangled with religious and political issues which are likely to cause friction (by definition, religious and political ideas are strongly valued by their beholder, so entering their specific topics in an open community is unlikely to end up being productive).

It's hard to say if your license violates the GitHub EULA or not, since it's a legal document which freely uses religious terminology taken from the scriptures. So this might depend on how you actually define some of these terms.

In particular, the terms "pure" and "impure" have very specific connotations in the Bible, especially in the Old Testament (where you'll find most of their occurrences). These terms are actually religious legal terms, since they usually refer to "legal purity/impurity", a topic which spans from ritual ablutions, dietary laws, meat preparation, and includes the definition of which sexual acts are to be considered pure or impure. The last part, if explicated, could easily result in a violation of GH terms, since it might result in discrimination and prejudice toward some sexual orientations.

I'm sure you understand well what I'm referring to here. Since you mention having knowledge of the Bible, you should be well aware of which biblical passages these might be, I believe that we can keep the conversation "subtle", without probing into issues that will raise controversy in the open. The problem here is that a license of this type is quite likely to raise such questions, it's just a matter of time.

The problem here is that on the one hand, you (as an organization) are the creators and definers of this license, but on the other hand you seem to delegate the user to the Bible for the interpretation of its fine clauses — and you'll admit that for a non Christian having to read and _understand_ the whole Bible is not a small feat, especially if he/she only wants to be able to use a software component.

IMO, you would do a great service to your users if you took upon yourself the task of defining some clearer guidelines as to what _you_ mean by terms like "good/bad", "pure/impure", etc., which is more than enough as far as this legal document is concerned — your document, your definitions, avoiding having to deal with the multitude of subjective interpretations.

Keeping these terms vague is not going to play out very well, IMO, and I see that many people have already expressed concerns about this. Please, try to understand that what might look familiar for you can be something that feels totally foreign to others. GitHub hosts people from all around the world, many of which might not have even had a Bible in their hands before: so it should not surprise you if so many people find it hard to decipher this license.

GitHub users take licenses very seriously — they want their software licenses to be honored, and so they are willing to honor others' licenses the best they can — but they also want to be sure they understand the terms they are accepting, and that they agree with these terms.

Somehow, I get the impression that this license is not playing out well in terms of clarity — it's not your usual and typical open source license. As for it claim of being ethical, it's hard to tell, it all depends on how it relates to some biblical "truths" which are deemed controversial and non-ethical by many atheists.

On GH people from all walks of live are welcome and should feel at home, regardless of their religion, nationality, or sexual orientation. Any material that _implicitly_ or _explicitly_ promotes views that discriminate against any specific group will be reported to GH Abuse.

**Comment by zicklag** [comment] 2021-12-11 16:32
@tajmone thank you for remaining civil and polite in your conversation.

> but doesn't it make more sense to discuss them here, since this is the official repository for the License?

To a certain extent yes, it just happened that the discussion was initially carried out on Bevy Retrograde because that was the first noticeable project under the license. It does make sense to comment here.

> My main concern here is that this license introduces some clauses which rub against the general spirit that drives the open source community, which (as mentioned) tries to avoid getting entangled with religious and political issues which are likely to cause friction (by definition, religious and political ideas are strongly valued by their beholder, so entering their specific topics in an open community is unlikely to end up being productive).

With that understanding, we as a group, are inevitably in a "pickle" so to speak, because we hold our beliefs to be the most important thing in our lives, but we still value the spirit sharing and collaboration that is prevalent in Open Source. To be clear, to us Open Source is second place to following our God, and the marrying of the two concepts will inevitably cause friction. So the only way to avoid the friction is to either not even attempt to make our software open, or to ignore our God, which we will not do.

> In particular, the terms "pure" and "impure" have very specific connotations in the Bible, especially in the Old Testament (where you'll find most of their occurrences). These terms are actually religious legal terms, since they usually refer to "legal purity/impurity", a topic which spans from ritual ablutions, dietary laws, meat preparation, and includes the definition of which sexual acts are to be considered pure or impure. The last part, if explicated, could easily result in a violation of GH terms, since it might result in discrimination and prejudice toward some sexual orientations.

As I've stated in other replies, the preamble, the only place where "pure" is used, has no bearing on the legal terms. The preamble, just like the preamble of the ubiquitous GPL license, is essentially only an "about us" for the license. The "why" of the license and the motivations which drove us to make the license.

The [latest version](https://github.com/katharostech/katharos-license/blob/master/LICENSE_v0.2.0_draft.md) of the license makes no reference to purity or the Bible in the terms. The terms are actually a combination of 3 totally un-religious licenses, the "No Harm" license, the "Hippocratic License", and the "GPL" ( with some modifications ).

This makes addresses all of the concerns about biblical interpretation or definition, etc. If you read only the legal terms of the license, you have no need to bring the Bible into it at all. The preamble, just like the GPL license, is not a list of legal rules that must be followed.

We have already acknowledged that certain terms regarding sexuality and violence are unclear and they will be clarified further in a next revision of our license.

> so it should not surprise you if so many people find it hard to decipher this license.

Actually, it seems that this license should be no harder to understand, if you read the terms, than the [Hippocratic License](https://firstdonoharm.dev/), from which our license was largely derived. The preamble seems to have confused people, with most people interpreting it as the terms of the license, and not our disclosure as to why we made the license.

The next draft of the license will be more clear to the point that the preamble has no legal bearing, and is just our message of why we made it.

> On GH people from all walks of live are welcome and should feel at home, regardless of their religion, nationality, or sexual orientation. Any material that implicitly or explicitly promotes views that discriminate against any specific group will be reported to GH Abuse.

We absolutely welcome people from all walks of life to use our software. We have never discriminated against anybody with our license or any of the things we have done or said in engaging with our community. We have been respectful and considerate, even when others have not shown the same respect to us.

Our license does **not** discriminate against _people_, it discriminates against _uses of our software_. Because it is our software, we have the right to say that people are not allowed to do certain things with it. Just like when Apple says you are not allowed to run a MacOS VM on a Windows machine. They get to make arbitrary rules about how their software is used. 

Just like the [author of the Hippocratic License mentions](https://github.com/EthicalSource/hippocratic-license/blob/eef3a5a4ecb731f34f45c01145e8ca4ba74c0714/content/faq.md#doesnt-the-hippocratic-license-violate-the-no-discrimination-and-fields-of-endeavor-terms-of-the-open-source-definition), our license applies equally to all peoples in all fields of endeavor and therefore doesn't discriminate against anybody.

---

When I get the chance, I will start on a third draft of the license. This will include:

  - An updated preamble making its separation from the terms of the license clear
  - An attempt to clarify the sexual and violence terms
  - Changing the license's arbitration rules from the "Hague Rules on Business and Human Rights Arbitration" to the [Kleros Court](https://github.com/katharostech/katharos-license/issues/3).

I will also create an FAQ to inform people about the common questions and answers regarding our license.

Hopefully that will clear some things up and allow any further discussion to cover topics not yet covered if any remain.

**Comment by tajmone** [comment] 2021-12-11 23:00
> With that understanding, we as a group, are inevitably in a "pickle" so to speak, because we hold our beliefs to be the most important thing in our lives, but we still value the spirit sharing and collaboration that is prevalent in Open Source. 

I believe that most of us are in the same "pickle" then, since it's reasonable that contributing to open source should be a secondary (or tertiary) value in our lives, and just a means to achieve goals which are motivated by higher (and more personal or communitarian) values and beliefs. And of course, the beauty behind the idea of open source collaboration is that it provides a neutral zone in which people can stop focusing on their differences and rather invest energy in what they mutually value.

I think the only reason why your license has raised concerns is because it mentions religious values in a license document (which, let's not forget, it's a legally binding contract). People in the open source community are used to see projects which are specifically targeting religious uses (e.g. prayers calendars, etc.), and that has never been cause of frictions, but licenses is something different.

> To be clear, to us Open Source is second place to following our God, and the marrying of the two concepts will inevitably cause friction. So the only way to avoid the friction is to either not even attempt to make our software open, or to ignore our God, which we will not do.

I don't think this is necessarily the case, really. I've seen quite a number of custom licenses impose restrictions to ensure "moral uses" of software — ranging from licenses which don't allow use by organizations involved in war, armaments (and their employers), to licenses that don't allow use by government agencies or employees of countries with death penalty, etc.

The whole idea of not allowing content which relate to sex, or are offensive, racist, promoting illegal activities, etc., is not new and as a matter a fact it's even to be found in GitHub EULA — and of course, some of these terms are subject to personal interpretation too, to a certain extent, but the EULA usually makes it clear that it's the service host who will ultimately decide what's "offensive", at its sole discretion.

> As I've stated in other replies, the preamble, the only place where "pure" is used, has no bearing on the legal terms. The preamble, just like the preamble of the ubiquitous GPL license, is essentially only an "about us" for the license. The "why" of the license and the motivations which drove us to make the license.

I'm not sure where you get the idea that a license preamble has no legal bearing. Everything in a license is part of the contract, and indeed the preamble is there to clarify the original intentions in case ambiguity of interpretation might arise (e.g. due to different juridical practices and principles of a given country).

In any case, regardless of what a license (or any other contract for that matter) claims, in a legal dispute the regional laws will take precedence over any claims which are in friction with the laws. Let's not forget that FOSS licenses are still somewhat in an "experimental" stage, for it's only in recent years that they had a chance to be challenged in legal courts — and these real world experiences, and the learned lessons therein, are now shaping these license with updated and revised versions of their text, in the hope to render them enforceable in as many countries as possible.

FOSS licenses are a rather delicate topic, especially when you consider that usually they end up being challenged in legal disputes of "huge corporations" vs "indy developers", where the formers are in for big profits (and have huge means in terms of lawyers and money to invest in cause), and usually the latter are ideologically motivated people who chose to share their work with others.

For these reasons, the general understanding is that introducing complexity in licenses tends to be counterproductive (especially if you're suing and have to cover legal expenses for any delays caused by interpretation ambiguities).

> The terms are actually a combination of 3 totally un-religious licenses, the "No Harm" license, the "Hippocratic License", and the "GPL" ( with some modifications ).

It would be fair to say that the "No Harm" license and the "Hippocratic License" have also raised similar concerns, and that are not considered the typical FOSS license either. Many people will object to the comparison with the GPL license, since its preamble sticks to the reality of the software world, which the FOSS community tends to understand in a fairly univocal manner.

> Juust like when Apple says you are not allowed to run a MacOS VM on a Windows machine. 

Ok, but Apple is doing that on their own products, in their own company, on their websites. Here we're speaking of GitHub, which is a private services with its own rules. I'm not sure how the GH community would welcome a software with a new license that would prevent its use on a specific OS when the software is capable of running on different OSs — probably it would be viewed as discrimination. We're not talking of what's _intrinsically_ right or wrong here, but what works with the community. If you look at the GitHub EULA, it's clear that many of its rules are _moral_ stances — pornography is not illegal in most countries, and freedom of speech doesn't prevent adults from using offensive language. The idea is to restrict the community to a certain ethos in order to provide a collaborative context that works well for the most (you can call it _tyranny of the majority_ if you like, that's perfectly fine, after all that's what democracy is in essence).

> This makes addresses all of the concerns about biblical interpretation or definition, etc. If you read only the legal terms of the license, you have no need to bring the Bible into it at all. The preamble, just like the GPL license, is not a list of legal rules that must be followed.

@zicklag, I hope you don't mind me taking the freedom of speculating on your motives, merely based on my personal experience. From what I've read so far (here and elsewhere) your motivations are to ensure that by sharing your work it won't be used to promote activities or values which are against your creed. I can totally understand your position, and I think it's fair that you should enforce such conditions (your work, your rules).

Based on my personal experience, having travelled the world and lived in different countries, including theocratic regimes, and having had the chance to interact with many different religions, and learnt from them, I can't avoid feeling that your preamble might actually turn out to be counterproductive to your goals.

I've lived in countries where Christians are relegated into ghettos because their creed goes against the official national creed (they're forbidden to wear crosses in public, or celebrate mass with wine), so I feel like I know what I'm talking about when I claim that your preamble to the license might actually prevent good Christians like you to use software with the katharos license in similar countries. 

(I won't enter into details here, since this is not the place for such discussions, but I can assure you I've seen things which broke my heart when it comes to the legal and social status Christians are subjected to in some countries today. I hope you'll never witness what I saw; it was painful for me, as an atheist, I can't imagine how hurtful it would be for a fellow Christian.)

On the other hand, it probably won't prevent its use for goals which you object to, in those same countries, since the preamble would render the license legally null (just like any contract bearing the name of J. is invalidated by law in such countries).

My understanding from my personal interactions with Christians has been that they consider good actions to be something universal — i.e. that a good action is such even if carried out by someone not affiliated to the religion. Which is why I think that by leaving the license preamble free from personal motivation you might actually ensure stronger guarantees for your goals. You could just focus on what you consider to be uses that go against your license (leaving out the why and source) and you'd be able to ensure more universality to your license. 

To some extent, each one of us wants to promote good and prevent evil, each one according to its own understanding of these terms. Unfortunately, in a legal contract there's only so much you can cover, so you'll have to settle with some practical definitions of use cases which are against your license (needless to say, something will always fall through the mesh).

I hope you don't mind me expressing my personal experiences here, and that I didn't overstep in my manners — in now way I intended to "teach you" how to go about with your religious understanding and decision making, I just wanted to share some personal considerations that you might have not considered.

I really appreciate your efforts in finding a balance between your personal faith and being able to share your precious work with the rest of the world, even if this forces you to face critics and friction. I hope that these exchanges might amount to constructive confrontations, and that you'll manage to find a solution other than segregating away from the FOSS community due to friction of views — that's the last thing I hope; it would be a failure reminding me of those ghettos I mentioned.

**Comment by zicklag** [comment] 2021-12-12 15:16
> I'm not sure where you get the idea that a license preamble has no legal bearing. Everything in a license is part of the contract, and indeed the preamble is there to clarify the original intentions in case ambiguity of interpretation might arise (e.g. due to different juridical practices and principles of a given country).
> ...
> It would be fair to say that the "No Harm" license and the "Hippocratic License" have also raised similar concerns, and that are not considered the typical FOSS license either. Many people will object to the comparison with the GPL license, since its preamble sticks to the reality of the software world, which the FOSS community tends to understand in a fairly univocal manner.
> ...
> For these reasons, the general understanding is that introducing complexity in licenses tends to be counterproductive (especially if you're suing and have to cover legal expenses for any delays caused by interpretation ambiguities).

Those are fair points! And I quite appreciate that you are reading and replying meaningfully to the statements I've made. :slightly_smiling_face: 

Our preamble _is_ quite different from the GPL license, and the GPL license does have this at the end of the preamble, which we are lacking: "The precise terms and conditions for copying, distribution and modification follow".

The whole document _is_ taken as the contract, regardless of whether it is called a "Preamble" or not, and the verbiage of the preamble itself, must make it clear that it is not to be interpreted as terms, if that is how the document is to be interpreted as a whole. That's something we need to improve on.

>  We're not talking of what's intrinsically right or wrong here, but what works with the community. If you look at the GitHub EULA, it's clear that many of its rules are moral stances — pornography is not illegal in most countries, and freedom of speech doesn't prevent adults from using offensive language. The idea is to restrict the community to a certain ethos in order to provide a collaborative context that works well for the most (you can call it tyranny of the majority if you like, that's perfectly fine, after all that's what democracy is in essence).

I think there are two perspectives you bring up here: GitHub as an organization, and the users of GitHub as a community.

I don't believe that GitHub as an organization cares how we license our software. If they deem our software as contrary to it's terms we will willingly take it off GitHub and move it somewhere else.

In terms of the GitHub community though, the response we've gotten has clearly shown that many do not appreciate the stance we've taken. Part of the issue is that we aren't looking for some ethos that the majority can agree on. We have a firm conviction of what our software shouldn't be used for, and that is what we seek to enforce, regardless of the majority.

We value democracy and freedom, but we also believe that it's within our freedoms to say that people shouldn't use what we've made to do what we believe is harm to other people.

> it probably won't prevent its use for goals which you object to, in those same countries, since the preamble would render the license legally null (just like any contract bearing the name of J. is invalidated by law in such countries).

This is a thought that we have not yet had, but having considered it, we believe that our preamble should still announce our religious convictions.

Our God has told us to share our faith with the world, and we truly believe that this license is something that He called us to author and to invoke His name within. God told us to “Go into all the world and preach the Good News to the whole creation”, and our license and preamble is a part of how we feel He's called us to do that.

If this means that the license itself is considered void in some countries, and that it is effectively unenforceable, then that is not optimal, but we believe that it is secondary to us sharing the truth of why we do what we do in our license. So we see the trade-off, and we believe that its worth it.

> @zicklag, I hope you don't mind me taking the freedom of speculating on your motives, merely based on my personal experience...I hope you don't mind me expressing my personal experiences here, and that I didn't overstep in my manners

To the contrary, I greatly appreciate the reason and respect you've shown here! You are exactly the kind of person that we _want_ to discuss our license with. You have brought sense and ideas to the discussion that have not been brought up before, and that is valuable and actually a help to us, so thank you, we appreciate that. Honest, constructive criticism is something we are always open to.

> I hope that these exchanges might amount to constructive confrontations, and that you'll manage to find a solution other than segregating away from the FOSS community due to friction of views — that's the last thing I hope; it would be a failure reminding me of those ghettos I mentioned.

Having to be separate in ways because of our faith is not something to be feared to us. While it's not preferable to have to be separate, we know and have known that our faith would cost us in different ways, maybe even in drastic ways, that is what Jesus said, but we believe that we have been given a promise and a hope that far outweighs the costs that we may face here. We may be different and even cast out, but our God is worth it.

Our whole goal with the license is to be as open and sharing as possible while doing our due diligence to prevent contributing to other people's harm. Whatever comes from it, we're confident that this is what we believe we were called to do, and that the license will accomplish God's purpose in one way or another, because it is _He_ that called us to make it.

We're still looking for any ways we can make it more useful to people, and your discussion has helped that. Not everybody will be happy with it, but hopefully we can clarify things as much as possible and make it useful to some people.

**Comment by zicklag** [comment] 2022-06-14 22:23
I've published an update to the license, the preamble, and the README. The README now contains our answers to frequently posed challenges regarding the license which should answer most questions.

I'm going to close this issue, but new issues may still be opened if points are not covered in the REDME.

**Closed as completed by zicklag** 2022-06-14 22:23 UTC
